name: CI/CD
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - run: yarn pb
      - uses: jwsi/secret-parser@v1
        with:
          filename: "functions/src/index.ts"
          secret-name: "MAILGUN"
          secret-value: "${{ secrets.MAILGUN }}"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_REOST_MC }}"
          channelId: live
          projectId: reost-mc
