name: CI/CD
on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 23 * * 0"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Yarn Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: ESLint
        run: yarn lint
      - name: Prebuild Step
        run: yarn pre-b
      - name: Build
        run: yarn build
      - name: Postbuild Step
        run: yarn post-b
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_REOST_MC }}"
          channelId: live
          projectId: reost-mc
