name: CI/CD
on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 23 * * 0"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: ESLint
        run: npm run lint
      - name: Prebuild Step
        run: npm run pre-b
      - name: Build
        run: npm run build
      - name: Postbuild Step
        run: npm run post-b
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_REOST_MC }}"
          channelId: live
          projectId: reost-mc
